@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njc5NDA5OTN9.EDRAHw-3mDQXp2EA3KAlXR3oHT8rLRwvt7JDCeUcmq0

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test2@test.com", 
  "password": "password",
  "password_confirmation": "password",
  "image_url": "test.png"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Trips index action
GET http://localhost:3000/trips.json
Authorization: Bearer {{jwt}}

### Trips create action
POST http://localhost:3000/trips.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "testing user_id = current_user.id in trip controller create action",
  "image_url": "test.png",
  "start_time": "2022-12-22",
  "end_time": "2022-12-23"
}

### Trips show action
GET http://localhost:3000/trips/3.json
Authorization: Bearer {{jwt}}

### Trips update action
PATCH http://localhost:3000/trips/5.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "testing user_id = current_user.id in trip controller create action!!",
  "image_url": "test.png",
  "start_time": "2022-12-22",
  "end_time": "2022-12-23"
}

### Trips destroy action
DELETE http://localhost:3000/trips/2.json
Authorization: Bearer {{jwt}}


### places index action
GET http://localhost:3000/places.json
Authorization: Bearer {{jwt}}

### places create action
POST http://localhost:3000/places.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "trip_id": 4, 
  "address": "testing places create action",
  "name": "test name",
  "description": "test description",
  "image_url": "test.png",
  "start_time": "2022-12-22",
  "end_time": "2022-12-23"
}

### places show action
GET http://localhost:3000/places/2.json
Authorization: Bearer {{jwt}}

### places update action
PATCH http://localhost:3000/places/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "trip_id": 1, 
  "address": "testing places update action!!!",
  "name": "test name",
  "description": "test description",
  "image_url": "test.png",
  "start_time": "2022-12-22",
  "end_time": "2022-12-23"
}

### places destroy action
DELETE http://localhost:3000/places/2.json
Authorization: Bearer {{jwt}}